name: DEV | Deploy CosmosDB Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_LOCATION: eastus
  RESOURCE_GROUP: rg-dev-autodilab

  BICEP_FILE: templates/bicep/main.cosmos.bicep
  BICEP_PARAM_FILE: templates/bicep/parameters/main-cosmos.dev.bicepparam

  FUNCTIONAPP_NAME: funcapp-ps-dev-sounak-updatetestcase
  FUNCTIONAPP_LISTENER_NAME: funcapp-ps-dev-sounak-eventlistner

jobs:
  deploy-dev:
    name: Deploy DEV Cosmos Infrastructure
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Validate Bicep
        run: |
          az deployment group validate \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }} \
            --parameters ${{ env.BICEP_PARAM_FILE }}

      - name: What-If (Preview Changes)
        run: |
          az deployment group what-if \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }} \
            --parameters ${{ env.BICEP_PARAM_FILE }}

      - name: Deploy Cosmos Bicep
        id: deployCosmos
        shell: bash
        run: |
          DEPLOY_OUTPUT=$(az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }} \
            --parameters ${{ env.BICEP_PARAM_FILE }} \
            --mode Incremental \
            --query properties.outputs \
            -o json)

          echo "cosmosDbEndpoint=$(echo $DEPLOY_OUTPUT | jq -r '.cosmosEndpoint.value')" >> $GITHUB_OUTPUT

      - name: Update Main Function App Settings
        run: |
          az functionapp config appsettings set \
            --name ${{ env.FUNCTIONAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings \
            CosmosEndpoint="${{ steps.deployCosmos.outputs.cosmosDbEndpoint }}"

      - name: Update Listener Function App Settings
        run: |
          az functionapp config appsettings set \
            --name ${{ env.FUNCTIONAPP_LISTENER_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings \
            CosmosEndpoint="${{ steps.deployCosmos.outputs.cosmosDbEndpoint }}"