name: DEV | Deploy Infrastructure - FA, KV, LA, AI, SA, AS 

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

env:
  AZURE_LOCATION: eastus
  RESOURCE_GROUP: rg-dev-autodilab
  BICEP_FILE: templates/bicep/main.bicep
  BICEP_PARAM_FILE: templates/bicep/parameters/main.dev.bicepparam

jobs:
  deploy-dev:
    name: Deploy DEV Infrastructure
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Validate Bicep
        run: |
          az deployment group validate \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }}\
            --parameters ${{ env.BICEP_PARAM_FILE }}

      - name: What-If (Preview Changes)
        run: |
          az deployment group what-if \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }} \
            --parameters ${{ env.BICEP_PARAM_FILE }}

      - name: Deploy Bicep to DEV
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ env.BICEP_FILE }} \
            --parameters ${{ env.BICEP_PARAM_FILE }} \
            --mode Incremental
